### ISSUE TITLE
Mun and Minmus (and possibly others) planetary strategies don't disable themselves after successfully doing either

### ISSUE THREAD

**Issue by smjjames** [jrossignol/Strategia#14]
For some reason, the Mun and Minmus programs are still available despite me having just done the Mun program one. 

Update: After I returned from a trip to Minmus, both manned and unmanned for those two are unavailable.
![strategiacareer_screenshot_2016-01-10--13-27-08](https://cloud.githubusercontent.com/assets/11197436/12224746/2bf865c0-b7ad-11e5-8f1f-6e8ea5cae75c.png)

**Comment by jrossignol** [comment]
The check for these had a problem, it's been fixed for the next release.
