### ISSUE TITLE
Sigma Binary Compatibility Issue

### ISSUE THREAD

**Issue by jrossignol** [jrossignol/Strategia#20]
Right now if Sigma Binary is installed, the Duna Program becomes the DunaIke program.  There's some logic that needs to be pulled in from Contract Configurator to handle this.

**Comment by jrossignol** [comment]
Fixed for 1.1.0

**Comment by sentania** [comment]
Just installed 1.1.0 on a KSP install w/ Duna-Ike + Sigma-Binary installed, and I still got The Duna Program, but I also got presented with the DunaIke Program

**Comment by jrossignol** [comment]
Thanks, there was an additional issue that I've now fixed.
