### ISSUE TITLE
Issues with To Boldly Go III

### ISSUE THREAD

**Issue by jrossignol** [jrossignol/Strategia#28]
From HenryBlatbugIII on [the forums](http://forum.kerbalspaceprogram.com/index.php?/topic/131808-105-strategia-v100-2016-02-10/&do=findComment&comment=2436405):

> Is it just me, or is anyone else not receiving bonuses from To Boldly Go?  It's correctly adjusting milestone funds rewards for non-Kerbin bodies (at level 3), but none of the levels have correctly given funds for the first science from a biome or body.

**Comment by jrossignol** [comment]
Have yet been able to reproduce this one.

**Comment by swilbur** [comment]
(I'm the same person from the KSP forum thread)

I just downloaded Strategia 1.1.0, and my initial tests seem to show that it's fixed.  I'm not sure what the problem was before.  Maybe it was interfering with one of my other mods.

**Comment by jrossignol** [comment]
Cool, might've been that I fixed it in the dev branch before you raised your issue.  As long as it's fixed now, I'll close the issue.  Thanks!
