### ISSUE TITLE
Funds values for the Minmus Program not matching up

### ISSUE THREAD

**Issue by Blu3wolf** [jrossignol/Strategia#43]
>Im not sure I understand the mission related Strategies incorrectly, or if I have a bug. Ive accepted the Minmus crewed strategy, which says it improves milestones funding rewards for minmus by 400%, and also says that it has an advance of 75K funds. Havent gotten to minmus to test the milestone rewards part just yet, but I also havent gotten the advance payment of 75K funds. Misunderstanding, or bug? 

>Have gotten to minmus now, and I did not get the 400% milestone reward either! I got 78,000 from the milestone, plus a bonus 62,400, instead of a bonus 312,000 funds. 

I dont have a log from just after accepting the strategy, although I can get one by starting a new save. This log is from shortly after entering Minmus' SOI.

**Comment by Blu3wolf** [comment]
http://www.blu3wolf.com/KSP/Strategia/output_log.txt
http://www.blu3wolf.com/KSP/Strategia/KSP.log

**Comment by Blu3wolf** [comment]
Perhaps its just the bonus value (in brackets) is not the +400% from Strategia? I mean, I think 78,000 is more than you normally get for entering Minmus' SOI on hard difficulty. Im not sure if it is a bug now.

**Comment by Blu3wolf** [comment]
Now Im seeing that the amount I get notified I am getting, is far less than what is actually added to my funds. Last two milestones were recovering a vessel from Minmus' and something else, both worth 70 something K funds, plus 60 something K bonus funds - any my total funds went up by about 100 K funds. Not exactly adding up at all!!

**Comment by jrossignol** [comment]
The first value is actually the total, and the value in brackets is the
additional.  So funds should increase by the first amount.

It's the way KSP displays it, and it's confusing.

**Comment by Blu3wolf** [comment]
Well dont I feel silly!

Okay, think its all working as intended then. -.-
