### ISSUE TITLE
Contract slot machine levels not working

### ISSUE THREAD

**Issue by jrossignol** [jrossignol/Strategia#74]
All the different levels of contract slot machine have the same numbers.  From ibanix on [the forums](https://forum.kerbalspaceprogram.com/index.php?/topic/131808-14x-strategia-v171-2018-04-02/&do=findComment&comment=3349417):

> Question: What do the upgrades to Contract Slot Machine do? They all seem to have the same description. 
> 
> They're all showing +50%/-50% for me. Need a save file/logs?

**Comment by fwdixon** [comment]
So was playing around with this one, but ran in to a knowledge hurdle. Is there a way to use the "levels" parameter to define a parameter group? The config file doesn't have any way for the code to know which effect goes to which level, so it just stops at the first lower and upper effect it reaches (the +- .5). I tried a few ways of introducing a logical test in the ExpandNode function (ConfigExpander.cs), but need to learn more about how nodes are defined to make it work I think.

**Comment by jrossignol** [comment]
I used to use the strategy commitment level to determine the level, but
removed it because it caused some of the requirement text to be confusing
("the admin facility doesn't support strategies at this commitment level"
or something like that).

That's what broke this - will need to add something in for the level.

**Comment by fwdixon** [comment]
Ah, will look forward to seeing what you come up with (learning about coding KSP mods by reading other people's source :D)

**Comment by jrossignol** [comment]
More from ibanix:

> Additionally, I'm noticing that the Advances on my contracts are now all negative numbers.
